export default {
  //HOME PAGE
  1: "BALANCE",
  2: "Send",
  3: "Receive",
  4: "LATEST TRANSACTIONS",
  5: "ID:",
  //SEND PAGE
  6: "SEND",
  7: "Enter Address",
  8: "Fee: ",
  9: "error",
  10: "Specify an address and amount",
  11: "Cancel",
  12: "Success",
  13: "You do not have enough funds",
  //RECEIVE PAGE
  14: "Warning",
  15: "Always make sure you backup your wallet or you risk losing your funds",
  16: "RECEIVE",
  17: "Copy",
  18: "Backup",
  19: "Copied to Clipboard",
  20: "Copied private key to clipboard",
  //LOGIN PAGE
  21: "Verify your ID",
  23: "Authorized",
  24: "PINs do not match",
  25: "PIN is incorrect",
  26: "Or use PIN",
  27: "Register a PIN",
  28: "Enter a PIN",
  29: "confirm PIN",
  30: "Register PIN",
  31: "Enter PIN",
  32: "Login",
  //SETTINGS PAGE
  33: "Delete Wallet",
  34: "Address and private key have been removed from device",
  35: "This will delete all wallet data from you device",
  36: "Go Back",
  //ones i forgot
  37: "Enter a username and password, this is only used to generate your wallet and you will not need to use it to sign in and it will not be stored anywhere even on your device",
  38: "Make sure that you are able to remember your credentials as they will be used to backup your wallet in future and there is no option to reset user credentials",
  39: "If you are trying to restore from backup, enter the same credentials below and your wallet will be imported to this device",
  40: "Username",
  41: "Password",
  42: "You do not have a connection to the internet. Please connect and try again. You will not have to do this again after wallet setup is completed",
  43: "Try Again",
  44: "If you have just sent a transaction wait until it has at least one 1 confirmation. If you mine to this address try sending smaller amounts to build up UTXOs",
  45: "There was an error reaching our server",
  46: "Import a wallet",
  47: "Create Wallet",
  48: "This will delete all current wallet data from you device and import a new wallet",
  49: "Import",
  50: "Private Key"
}
