export default {
// PAGE D'ACCUEIL
  1: "BALANCE",
  2: "envoyer",
  3: "Recevoir",
  4: "DERNIÈRES TRANSACTIONS",
  5: "ID:",
  // ENVOYER PAGE
  6: "ENVOYER",
  7: "Entrez l'adresse",
  8: "Frais:",
  9: "erreur",
  10: "Spécifiez une adresse et un montant",
  11: "Annuler",
  12: "Succès",
  13: "Vous n'avez pas assez de fonds",
  // RECEVOIR PAGE
  14: "Avertissement",
  15: "Assurez-vous toujours de sauvegarder vos portefeuille ou vous risquez de perdre vos fonds",
  16: "RECEVOIR",
  17: "Copier",
  18: "Sauvegarde",
  19: "Copié dans le presse-papier",
  20: "Clé privée copiée dans le presse-papier",
  //PAGE DE CONNEXION
  21: "Vérifiez votre identité",
  23: "autorisé",
  24: "Les codes confidentiels ne correspondent pas",
  25: "Le code PIN est incorrect",
  26: "Ou utilisez un code PIN",
  27: "Enregistrer un code PIN",
  28: "Entrez un code PIN",
  29: "confirmer le code PIN",
  30: "Enregistrer le code PIN",
  31: "Entrer code PIN",
  32: "Login",
  // page paramètres
  33: "Supprimer le portefeuille",
  34: "Adresse et clé privée ont été retiré de l'appareil",
  35: "Ceci supprimera toutes les données du portefeuille de vous appareil",
  36: "Go Back",
  // ceux que j'ai oubliés
  37: "Entrez un nom d'utilisateur et un mot de passe, cette est uniquement utilisé pour générer votre portefeuille et vous n'aura pas besoin de l'utiliser pour vous connecter et ne sera stocké nulle part même sur votre dispositif",
  38: "Assurez-vous que vous êtes capable de rappelez-vous vos informations d'identification telles qu'elles seront utilisé pour sauvegarder votre portefeuille à l'avenir et il n'y a pas d'option pour réinitialiser l'utilisateur lettres de créance",
  39: "Si vous essayez de restaurer à partir de sauvegarde, entrez les mêmes identifiants ci-dessous et votre portefeuille sera importé dans cette dispositif",
  40: "Nom d'utilisateur",
  41: "Mot de passe",
  42: "Vous n’avez pas de connexion au l'Internet. Veuillez vous connecter et réessayer. Vous n'aura pas à le refaire après la la configuration du portefeuille est terminée",
  43: "Essaie encore",
  44: "Si vous venez d'envoyer une transaction attendez qu'il en ait au moins un 1 confirmation. Si vous minez à cette adresse essayez d'envoyer de plus petites quantités à accumuler UTXOs ",
  45: "Il y a eu une erreur en atteignant notre serveur",
  46: "Importer un portefeuille",
  47: "Créer un portefeuille",
  48: "Cela supprimera toutes les données de portefeuille actuelles de cet appareil et importera un nouveau portefeuille",
  49: "Importation",
  50: "Clé privée"
}
